// @ts-nocheck
/**
 * Wallet Constants
 * Core constants for the NEX Points economy system
 * Prepared for future migration to NEX COIN token
 */

const WALLET_CONFIG = {
  CURRENCY_NAME: "NEX Points",
  CURRENCY_SYMBOL: "NEX",
  FUTURE_TOKEN_NAME: "NEX COIN",
  FUTURE_TOKEN_SYMBOL: "NEX",
};

const TRANSACTION_TYPES = {
  EARN: "earn",
  SPEND: "spend",
  GIFT: "gift",
  REWARD: "reward",
  BONUS: "bonus",
  REFERRAL: "referral",
  ADMIN_ADJUSTMENT: "admin_adjustment",
  TRANSFER: "transfer",
};

const TRANSACTION_SOURCES = {
  DAILY_LOGIN: "daily_login",
  VIDEO_UPLOAD: "video_upload",
  LIVE_STREAM: "live_stream",
  GIFT_SENT: "gift_sent",
  GIFT_RECEIVED: "gift_received",
  REFERRAL: "referral",
  SYSTEM_BONUS: "system_bonus",
  CREATOR_EARNINGS: "creator_earnings",
  PURCHASE: "purchase",
  ADMIN_MANUAL: "admin_manual",
  REFUND: "refund",
  TRENDING_CONTENT: "trending_content",
  FIRST_TIME_BONUS: "first_time_bonus",
  REDEEM: "redeem",
  QR_TRANSFER: "qr_transfer",
  TRANSFER: "transfer",
  POST_VIEW: "post_view",
  LIKE_REWARD: "like_reward",
  COMMENT_REWARD: "comment_reward",
  SHARE_REWARD: "share_reward",
  PROFILE_VISIT: "profile_visit",
  FOLLOW_REWARD: "follow_reward",
  WATCH_TIME: "watch_time",
};

const TRANSACTION_STATUS = {
  COMPLETED: "completed",
  PENDING: "pending",
  FAILED: "failed",
  REVERSED: "reversed",
};

// Reward amounts for different activities
const REWARD_AMOUNTS = {
  DAILY_LOGIN: 10,
  VIDEO_UPLOAD: 20,
  LIVE_STREAM_START: 50,
  REFERRAL_SIGNUP: 50,
  TRENDING_CONTENT: 200,
  FIRST_TIME_BONUS: 500,
};

// User levels based on lifetime earned
const USER_LEVELS = {
  STARTER: { level: 1, minPoints: 0, name: "Starter" },
  CLIMBER: { level: 2, minPoints: 500, name: "Climber" },
  INFLUENCER: { level: 3, minPoints: 2000, name: "Influencer" },
  SUPERSTAR: { level: 4, minPoints: 5000, name: "Superstar" },
  LEGEND: { level: 5, minPoints: 10000, name: "Legend" },
};

const GIFT_DEFINITIONS = {
  HEART: {
    id: "heart",
    name: "Heart",
    color: "rose",
    pointsCost: 1,
    creatorRewardPercent: 50,
    animation: "floating_hearts",
    emoji: "❤️",
    tier: "small",
  },
  ROSE: {
    id: "rose",
    name: "Rose",
    color: "red",
    pointsCost: 5,
    creatorRewardPercent: 50,
    animation: "flying_roses",
    emoji: "🌹",
    tier: "small",
  },
  FLOWER_BOUQUET: {
    id: "flower_bouquet",
    name: "Flower Bouquet",
    color: "pink",
    pointsCost: 15,
    creatorRewardPercent: 55,
    animation: "bouquet_bloom",
    emoji: "💐",
    tier: "small",
  },
  FIRE: {
    id: "fire",
    name: "Fire",
    color: "orange",
    pointsCost: 10,
    creatorRewardPercent: 60,
    animation: "fire_burst",
    emoji: "🔥",
    tier: "small",
  },
  DIAMOND: {
    id: "diamond",
    name: "Diamond",
    color: "cyan",
    pointsCost: 25,
    creatorRewardPercent: 65,
    animation: "diamond_sparkle",
    emoji: "💎",
    tier: "small",
  },
  CROWN: {
    id: "crown",
    name: "Crown",
    color: "gold",
    pointsCost: 50,
    creatorRewardPercent: 70,
    animation: "crown_shine",
    emoji: "👑",
    tier: "medium",
  },
  ROCKET: {
    id: "rocket",
    name: "Rocket",
    color: "blue",
    pointsCost: 100,
    creatorRewardPercent: 75,
    animation: "rocket_launch",
    emoji: "🚀",
    tier: "medium",
  },
  SPORTS_CAR: {
    id: "sports_car",
    name: "Sports Car",
    color: "red",
    pointsCost: 250,
    creatorRewardPercent: 75,
    animation: "car_sweep",
    emoji: "🏎️",
    tier: "medium",
  },
  MAGIC_BOX: {
    id: "magic_box",
    name: "Magic Box",
    color: "violet",
    pointsCost: 500,
    creatorRewardPercent: 78,
    animation: "magic_box",
    emoji: "🎁",
    tier: "medium",
  },
  LION: {
    id: "lion",
    name: "Lion",
    color: "amber",
    pointsCost: 1000,
    creatorRewardPercent: 75,
    animation: "lion_roar",
    emoji: "🦁",
    tier: "premium",
  },
  UNIVERSE: {
    id: "universe",
    name: "Universe",
    color: "violet",
    pointsCost: 5000,
    creatorRewardPercent: 85,
    animation: "universe_burst",
    emoji: "🌌",
    tier: "premium",
  },
  CASTLE: {
    id: "castle",
    name: "Castle",
    color: "indigo",
    pointsCost: 2000,
    creatorRewardPercent: 82,
    animation: "castle_glow",
    emoji: "🏰",
    tier: "premium",
  },
  DRAGON: {
    id: "dragon",
    name: "Dragon",
    color: "emerald",
    pointsCost: 3000,
    creatorRewardPercent: 84,
    animation: "dragon_flight",
    emoji: "🐉",
    tier: "premium",
  },
  GALAXY_STORM: {
    id: "galaxy_storm",
    name: "Galaxy Storm",
    color: "fuchsia",
    pointsCost: 7500,
    creatorRewardPercent: 88,
    animation: "galaxy_storm",
    emoji: "✨",
    tier: "premium",
  },
};

Object.assign(GIFT_DEFINITIONS, {
  HEART: {
    id: "heart",
    name: "Heart",
    color: "rose",
    colors: ["#fb7185", "#f43f5e", "#ffffff"],
    pointsCost: 1,
    creatorRewardPercent: 50,
    animation: "floating_hearts",
    animationStyle: "float",
    animationDuration: 1800,
    comboMultiplier: 1,
    rarity: "common",
    emoji: "\u2764\uFE0F",
    tier: "small",
    soundReady: true,
  },
  ROSE: {
    id: "rose",
    name: "Rose",
    color: "red",
    colors: ["#f43f5e", "#be123c", "#fecdd3"],
    pointsCost: 5,
    creatorRewardPercent: 50,
    animation: "flying_roses",
    animationStyle: "spiral",
    animationDuration: 2100,
    comboMultiplier: 1.1,
    rarity: "common",
    emoji: "\uD83C\uDF39",
    tier: "small",
    soundReady: true,
  },
  FLOWER: {
    id: "flower",
    name: "Flower",
    color: "pink",
    colors: ["#f9a8d4", "#a78bfa", "#86efac"],
    pointsCost: 10,
    creatorRewardPercent: 55,
    animation: "flower_bloom",
    animationStyle: "bloom",
    animationDuration: 2200,
    comboMultiplier: 1.15,
    rarity: "common",
    emoji: "\uD83C\uDF38",
    tier: "small",
    soundReady: true,
  },
  LIKE: {
    id: "like",
    name: "Like",
    color: "blue",
    colors: ["#60a5fa", "#22d3ee", "#ffffff"],
    pointsCost: 15,
    creatorRewardPercent: 55,
    animation: "like_pop",
    animationStyle: "pop",
    animationDuration: 1700,
    comboMultiplier: 1.15,
    rarity: "common",
    emoji: "\uD83D\uDC4D",
    tier: "small",
    soundReady: true,
  },
  COFFEE: {
    id: "coffee",
    name: "Coffee",
    color: "amber",
    colors: ["#f59e0b", "#92400e", "#fde68a"],
    pointsCost: 15,
    creatorRewardPercent: 55,
    animation: "coffee_steam",
    animationStyle: "steam",
    comboMultiplier: 1.15,
    rarity: "common",
    emoji: "\u2615",
    tier: "small",
  },
  FIRE: {
    id: "fire",
    name: "Fire",
    color: "orange",
    colors: ["#fb923c", "#ef4444", "#fef3c7"],
    pointsCost: 25,
    creatorRewardPercent: 60,
    animation: "fire_burst",
    animationStyle: "burst",
    animationDuration: 2400,
    comboMultiplier: 1.25,
    rarity: "rare",
    emoji: "\uD83D\uDD25",
    tier: "small",
    soundReady: true,
  },
  CROWN: {
    id: "crown",
    name: "Crown",
    color: "gold",
    colors: ["#facc15", "#f97316", "#fff7ed"],
    pointsCost: 50,
    creatorRewardPercent: 70,
    animation: "crown_shine",
    animationStyle: "shine",
    animationDuration: 2600,
    comboMultiplier: 1.35,
    rarity: "rare",
    emoji: "\uD83D\uDC51",
    tier: "medium",
    soundReady: true,
  },
  DIAMOND: {
    id: "diamond",
    name: "Diamond",
    color: "cyan",
    colors: ["#67e8f9", "#38bdf8", "#ffffff"],
    pointsCost: 150,
    creatorRewardPercent: 72,
    animation: "diamond_sparkle",
    animationStyle: "sparkle",
    animationDuration: 2800,
    comboMultiplier: 1.65,
    rarity: "epic",
    emoji: "\uD83D\uDC8E",
    tier: "medium",
    soundReady: true,
  },
  ROCKET: {
    id: "rocket",
    name: "Rocket",
    color: "blue",
    colors: ["#60a5fa", "#f97316", "#f8fafc"],
    pointsCost: 100,
    creatorRewardPercent: 75,
    animation: "rocket_launch",
    animationStyle: "launch",
    animationDuration: 2800,
    comboMultiplier: 1.5,
    rarity: "rare",
    emoji: "\uD83D\uDE80",
    tier: "medium",
    soundReady: true,
  },
  SUPER_CHAT: {
    id: "super_chat",
    name: "Super Chat",
    color: "blue",
    colors: ["#a78bfa", "#2563eb", "#f8fafc"],
    pointsCost: 200,
    creatorRewardPercent: 76,
    animation: "super_chat_wave",
    animationStyle: "wave",
    animationDuration: 3000,
    comboMultiplier: 1.75,
    rarity: "epic",
    emoji: "\uD83D\uDCAC",
    tier: "medium",
    soundReady: true,
  },
  MUSIC: {
    id: "music",
    name: "Music",
    color: "emerald",
    colors: ["#34d399", "#06b6d4", "#ecfeff"],
    pointsCost: 250,
    creatorRewardPercent: 78,
    animation: "music_notes",
    animationStyle: "notes",
    animationDuration: 3000,
    comboMultiplier: 1.85,
    rarity: "epic",
    emoji: "\uD83C\uDFB5",
    tier: "medium",
    soundReady: true,
  },
  LION: {
    id: "lion",
    name: "Lion",
    color: "amber",
    colors: ["#f59e0b", "#d97706", "#fff7ed"],
    pointsCost: 500,
    creatorRewardPercent: 80,
    animation: "lion_roar",
    animationStyle: "fullscreen_roar",
    comboMultiplier: 2.2,
    rarity: "legendary",
    emoji: "\uD83E\uDD81",
    tier: "premium",
    fullscreen: true,
    soundReady: true,
  },
  CASTLE: {
    id: "castle",
    name: "Castle",
    color: "indigo",
    colors: ["#818cf8", "#312e81", "#f5f3ff"],
    pointsCost: 750,
    creatorRewardPercent: 82,
    animation: "castle_glow",
    animationStyle: "glow_cascade",
    animationDuration: 4200,
    comboMultiplier: 2.45,
    rarity: "legendary",
    emoji: "\uD83C\uDFF0",
    tier: "premium",
    fullscreen: true,
    soundReady: true,
  },
  GALAXY: {
    id: "galaxy",
    name: "Galaxy",
    color: "fuchsia",
    colors: ["#e879f9", "#4f46e5", "#22d3ee"],
    pointsCost: 900,
    creatorRewardPercent: 84,
    animation: "galaxy_swirl",
    animationStyle: "swirl",
    animationDuration: 4500,
    comboMultiplier: 2.6,
    rarity: "mythic",
    emoji: "\uD83C\uDF0C",
    tier: "premium",
    fullscreen: true,
    soundReady: true,
  },
  VIBEBOOK_BOOK: {
    id: "vibebook_book",
    name: "VibeBook Gift",
    color: "teal",
    colors: ["#14b8a6", "#2563eb", "#a7f3d0"],
    pointsCost: 1000,
    creatorRewardPercent: 88,
    animation: "vibebook_3d_book",
    animationStyle: "fullscreen_3d_book",
    animationDuration: 5200,
    comboMultiplier: 3,
    rarity: "exclusive",
    emoji: "\uD83D\uDCD8",
    tier: "premium",
    fullscreen: true,
    special: true,
    soundReady: true,
  },
  JET: {
    id: "jet",
    name: "Jet",
    color: "blue",
    colors: ["#93c5fd", "#1d4ed8", "#f8fafc"],
    pointsCost: 1200,
    creatorRewardPercent: 86,
    animation: "jet_flyby",
    animationStyle: "fullscreen_flyby",
    animationDuration: 4600,
    comboMultiplier: 3.2,
    rarity: "mythic",
    emoji: "\u2708\uFE0F",
    tier: "premium",
    fullscreen: true,
    soundReady: true,
  },
  DRAGON: {
    id: "dragon",
    name: "Dragon",
    color: "emerald",
    colors: ["#34d399", "#064e3b", "#f8fafc"],
    pointsCost: 1500,
    creatorRewardPercent: 88,
    animation: "dragon_flight",
    animationStyle: "fullscreen_sweep",
    animationDuration: 5000,
    comboMultiplier: 3.5,
    rarity: "mythic",
    emoji: "\uD83D\uDC09",
    tier: "premium",
    fullscreen: true,
    soundReady: true,
  },
  UNIVERSE: {
    id: "universe",
    name: "Universe",
    color: "violet",
    colors: ["#c084fc", "#1e1b4b", "#38bdf8"],
    pointsCost: 1200,
    creatorRewardPercent: 85,
    animation: "universe_burst",
    animationStyle: "fullscreen_burst",
    comboMultiplier: 3.2,
    rarity: "mythic",
    emoji: "\uD83C\uDF20",
    tier: "premium",
    fullscreen: true,
    soundReady: true,
  },
  GOLDEN_CROWN: {
    id: "golden_crown",
    name: "Golden Crown",
    color: "gold",
    colors: ["#facc15", "#f59e0b", "#ffffff"],
    pointsCost: 1500,
    creatorRewardPercent: 90,
    animation: "golden_crown_coronation",
    animationStyle: "fullscreen_coronation",
    comboMultiplier: 3.5,
    rarity: "exclusive",
    emoji: "\uD83D\uDC51",
    tier: "premium",
    fullscreen: true,
    soundReady: true,
  },
});

const DAILY_LOGIN_COOLDOWN_MS = 24 * 60 * 60 * 1000; // 24 hours
const VIDEO_UPLOAD_COOLDOWN_MS = 60 * 1000; // 1 minute (prevent spam)
const TRANSFER_COOLDOWN_MS = 60 * 1000; // 1 minute (prevent spam)
const REFERRAL_COOLDOWN_MS = 7 * 24 * 60 * 60 * 1000; // 7 days (per referral unique)

module.exports = {
  WALLET_CONFIG,
  TRANSACTION_TYPES,
  TRANSACTION_SOURCES,
  TRANSACTION_STATUS,
  REWARD_AMOUNTS,
  USER_LEVELS,
  GIFT_DEFINITIONS,
  DAILY_LOGIN_COOLDOWN_MS,
  VIDEO_UPLOAD_COOLDOWN_MS,
  TRANSFER_COOLDOWN_MS,
  REFERRAL_COOLDOWN_MS,
};
