// @ts-nocheck
const MARKETPLACE_CATEGORIES = {
  FRAMES: "frames",
  BADGES: "badges",
  BOOSTS: "boosts",
  REACTIONS: "reactions",
  FEATURED: "featured",
  THEMES: "themes",
  GIFTS: "gifts",
};

const RARITIES = {
  COMMON: "common",
  RARE: "rare",
  EPIC: "epic",
  LEGENDARY: "legendary",
  MYTHIC: "mythic",
  SEASONAL: "seasonal",
};

const PREMIUM_FRAME_ITEMS = [
  {
    itemId: "frame_starter_neon",
    name: "Starter Neon",
    category: MARKETPLACE_CATEGORIES.FRAMES,
    rarity: RARITIES.COMMON,
    price: 50,
    levelRequired: 1,
    description: "Clean neon creator frame with soft animated glow for first NEX store unlocks.",
    preview: { gradient: "from-cyan-300 via-lime-300 to-emerald-500", icon: "sparkles", animation: "pulse", frameStyle: "neon" },
    metadata: { frameStyle: "neon", animation: "neon-pulse", aura: "cyan", collection: "Neon Creator Frames" },
  },
  {
    itemId: "frame_gold_aura",
    name: "Gold Aura",
    category: MARKETPLACE_CATEGORIES.FRAMES,
    rarity: RARITIES.RARE,
    price: 250,
    levelRequired: 1,
    description: "Royal gold profile frame with glass depth, metallic sweep, and creator status shine.",
    preview: { gradient: "from-yellow-200 via-amber-400 to-orange-600", icon: "crown", animation: "shine", frameStyle: "royal" },
    metadata: { frameStyle: "royal", animation: "gold-shimmer", aura: "gold", collection: "Royal Gold Frames" },
  },
  {
    itemId: "frame_anime_energy",
    name: "Anime Energy",
    category: MARKETPLACE_CATEGORIES.FRAMES,
    rarity: RARITIES.RARE,
    price: 320,
    levelRequired: 1,
    description: "High-energy creator frame with electric streaks, motion arcs, and bold fan-page attitude.",
    preview: { gradient: "from-pink-400 via-violet-500 to-sky-400", icon: "zap", animation: "orbit", frameStyle: "anime" },
    metadata: { frameStyle: "anime", animation: "energy-orbit", aura: "violet", collection: "Anime Energy Frames" },
  },
  {
    itemId: "frame_cyber_matrix",
    name: "Cyber Matrix",
    category: MARKETPLACE_CATEGORIES.FRAMES,
    rarity: RARITIES.EPIC,
    price: 650,
    levelRequired: 2,
    description: "Futuristic cyber frame with scanner lines, blue glass, and next-gen creator finance energy.",
    preview: { gradient: "from-slate-950 via-blue-600 to-teal-300", icon: "radio", animation: "pulse", frameStyle: "cyber" },
    metadata: { frameStyle: "cyber", animation: "cyber-scan", aura: "blue", collection: "Futuristic Cyber Frames" },
  },
  {
    itemId: "frame_kigali_night",
    name: "Kigali Night",
    category: MARKETPLACE_CATEGORIES.FRAMES,
    rarity: RARITIES.EPIC,
    price: 780,
    levelRequired: 2,
    description: "Kigali nightlife inspired frame with city-light gradients, warm glow, and premium social depth.",
    preview: { gradient: "from-indigo-950 via-fuchsia-600 to-yellow-300", icon: "star", animation: "shine", frameStyle: "kigali" },
    metadata: { frameStyle: "kigali", animation: "city-lights", aura: "nightlife", collection: "Kigali Nightlife Frames" },
  },
  {
    itemId: "frame_diamond_elite",
    name: "Diamond Elite",
    category: MARKETPLACE_CATEGORIES.FRAMES,
    rarity: RARITIES.LEGENDARY,
    price: 1200,
    levelRequired: 3,
    description: "Diamond elite frame with crystalline highlights, cool luxury shadows, and animated sparkle depth.",
    preview: { gradient: "from-cyan-200 via-white to-violet-500", icon: "gem", animation: "sparkle", frameStyle: "diamond" },
    metadata: { frameStyle: "diamond", animation: "diamond-sparkle", aura: "crystal", collection: "Diamond Elite Frames" },
  },
  {
    itemId: "frame_flame_aura",
    name: "Flame Aura",
    category: MARKETPLACE_CATEGORIES.FRAMES,
    rarity: RARITIES.EPIC,
    price: 900,
    levelRequired: 2,
    description: "Animated flame aura for viral creators, live clips, and high-heat profile moments.",
    preview: { gradient: "from-orange-300 via-red-500 to-rose-700", icon: "flame", animation: "flicker", frameStyle: "flame" },
    metadata: { frameStyle: "flame", animation: "fire-flicker", aura: "fire", collection: "Flame Aura Frames" },
  },
  {
    itemId: "frame_vip_prestige",
    name: "VIP Prestige",
    category: MARKETPLACE_CATEGORIES.FRAMES,
    rarity: RARITIES.LEGENDARY,
    price: 1800,
    levelRequired: 4,
    description: "VIP creator frame with dark glass, status rails, gold accents, and subtle prestige motion.",
    preview: { gradient: "from-zinc-950 via-amber-500 to-white", icon: "shield-check", animation: "shine", frameStyle: "vip" },
    metadata: { frameStyle: "vip", animation: "prestige-sweep", aura: "vip", collection: "VIP Prestige Frames" },
  },
  {
    itemId: "frame_minimal_luxury",
    name: "Minimal Luxury",
    category: MARKETPLACE_CATEGORIES.FRAMES,
    rarity: RARITIES.RARE,
    price: 180,
    levelRequired: 1,
    description: "Minimal luxury frame with thin platinum lines, quiet glow, and polished creator branding.",
    preview: { gradient: "from-slate-100 via-zinc-300 to-slate-800", icon: "badge-check", animation: "shine", frameStyle: "minimal" },
    metadata: { frameStyle: "minimal", animation: "platinum-line", aura: "platinum", collection: "Minimal Luxury Frames" },
  },
  {
    itemId: "frame_nex_genesis_founder",
    name: "NEX Genesis Founder",
    category: MARKETPLACE_CATEGORIES.FRAMES,
    rarity: RARITIES.MYTHIC,
    price: 5000,
    levelRequired: 5,
    description: "Founder-exclusive genesis frame for the first wave of VibeBook future creator finance leaders.",
    preview: { gradient: "from-black via-lime-300 to-cyan-200", icon: "trophy", animation: "orbit", frameStyle: "genesis" },
    metadata: { frameStyle: "genesis", animation: "genesis-orbit", aura: "founder", founderExclusive: true, collection: "NEX Genesis Founder Frames" },
  },
];

const DEFAULT_MARKETPLACE_ITEMS = [
  ...PREMIUM_FRAME_ITEMS,
  {
    itemId: "frame_neon_glow",
    name: "Neon Glow",
    category: MARKETPLACE_CATEGORIES.FRAMES,
    rarity: RARITIES.RARE,
    price: 250,
    levelRequired: 1,
    description: "Animated green neon ring for profiles, comments, chats, and ranks.",
    preview: { gradient: "from-emerald-300 via-cyan-300 to-lime-300", icon: "sparkles", animation: "pulse" },
    metadata: { animation: "neon-pulse", aura: "emerald" },
  },
  {
    itemId: "frame_gold_elite",
    name: "Gold Elite",
    category: MARKETPLACE_CATEGORIES.FRAMES,
    rarity: RARITIES.EPIC,
    price: 700,
    levelRequired: 2,
    description: "Luxury creator border with a warm gold sweep.",
    preview: { gradient: "from-yellow-200 via-amber-400 to-orange-500", icon: "crown", animation: "shine" },
    metadata: { animation: "gold-shimmer", aura: "gold" },
  },
  {
    itemId: "frame_fire_aura",
    name: "Fire Aura",
    category: MARKETPLACE_CATEGORIES.FRAMES,
    rarity: RARITIES.EPIC,
    price: 900,
    levelRequired: 3,
    description: "Hot creator frame for viral moments and high-energy posts.",
    preview: { gradient: "from-orange-400 via-red-500 to-rose-600", icon: "flame", animation: "flicker" },
    metadata: { animation: "fire-flicker", aura: "fire" },
  },
  {
    itemId: "frame_diamond_ring",
    name: "Diamond Ring",
    category: MARKETPLACE_CATEGORIES.FRAMES,
    rarity: RARITIES.LEGENDARY,
    price: 1600,
    levelRequired: 4,
    description: "Diamond sparkle frame reserved for elite earners.",
    preview: { gradient: "from-cyan-200 via-sky-400 to-violet-500", icon: "gem", animation: "sparkle" },
    metadata: { animation: "diamond-sparkle", aura: "crystal" },
  },
  {
    itemId: "frame_rwanda_pride",
    name: "Rwanda Pride",
    category: MARKETPLACE_CATEGORIES.FRAMES,
    rarity: RARITIES.SEASONAL,
    price: 500,
    levelRequired: 1,
    description: "A Rwanda-inspired celebration frame for culture-forward creators.",
    preview: { gradient: "from-sky-500 via-yellow-300 to-emerald-500", icon: "star", animation: "wave" },
    metadata: { animation: "flag-wave", aura: "rwanda" },
  },
  {
    itemId: "frame_creator_legend",
    name: "Creator Legend",
    category: MARKETPLACE_CATEGORIES.FRAMES,
    rarity: RARITIES.MYTHIC,
    price: 3200,
    levelRequired: 5,
    description: "Top prestige aura for platform-defining creators.",
    preview: { gradient: "from-fuchsia-400 via-amber-300 to-cyan-300", icon: "trophy", animation: "orbit" },
    metadata: { animation: "legend-orbit", aura: "legend" },
  },
  {
    itemId: "frame_cyber_pulse",
    name: "Cyber Pulse",
    category: MARKETPLACE_CATEGORIES.FRAMES,
    rarity: RARITIES.RARE,
    price: 420,
    levelRequired: 1,
    description: "Fast cyber pulse frame for tech and gaming creators.",
    preview: { gradient: "from-blue-500 via-indigo-500 to-teal-300", icon: "zap", animation: "pulse" },
    metadata: { animation: "cyber-pulse", aura: "cyber" },
  },
  {
    itemId: "badge_verified_creator",
    name: "Verified Creator",
    category: MARKETPLACE_CATEGORIES.BADGES,
    rarity: RARITIES.EPIC,
    price: 1200,
    levelRequired: 2,
    durationDays: 30,
    description: "Thirty-day verified creator badge with animated check shimmer.",
    preview: { gradient: "from-sky-400 to-blue-600", icon: "badge-check", animation: "shine" },
    metadata: { label: "Verified", badgeTone: "sky" },
  },
  {
    itemId: "badge_rising_star",
    name: "Rising Star",
    category: MARKETPLACE_CATEGORIES.BADGES,
    rarity: RARITIES.RARE,
    price: 350,
    levelRequired: 1,
    description: "Permanent badge for new creators building momentum.",
    preview: { gradient: "from-lime-300 to-emerald-500", icon: "star", animation: "pulse" },
    metadata: { label: "Rising", badgeTone: "emerald" },
  },
  {
    itemId: "badge_top_streamer",
    name: "Top Streamer",
    category: MARKETPLACE_CATEGORIES.BADGES,
    rarity: RARITIES.LEGENDARY,
    price: 1800,
    levelRequired: 3,
    durationDays: 14,
    description: "Timed status badge for live and short-form power creators.",
    preview: { gradient: "from-purple-400 to-fuchsia-600", icon: "radio", animation: "pulse" },
    metadata: { label: "Top Streamer", badgeTone: "purple" },
  },
  {
    itemId: "badge_elite_creator",
    name: "Elite Creator",
    category: MARKETPLACE_CATEGORIES.BADGES,
    rarity: RARITIES.LEGENDARY,
    price: 2100,
    levelRequired: 4,
    description: "Permanent badge for creators who want profile-first status.",
    preview: { gradient: "from-amber-300 to-yellow-600", icon: "medal", animation: "shine" },
    metadata: { label: "Elite", badgeTone: "amber" },
  },
  {
    itemId: "badge_trend_king",
    name: "Trend King",
    category: MARKETPLACE_CATEGORIES.BADGES,
    rarity: RARITIES.EPIC,
    price: 1000,
    levelRequired: 2,
    durationDays: 7,
    description: "Seasonal trending badge for feed domination weeks.",
    preview: { gradient: "from-red-500 to-orange-400", icon: "flame", animation: "flicker" },
    metadata: { label: "Trend King", badgeTone: "red" },
  },
  {
    itemId: "badge_og_creator",
    name: "OG Creator",
    category: MARKETPLACE_CATEGORIES.BADGES,
    rarity: RARITIES.MYTHIC,
    price: 2600,
    levelRequired: 5,
    description: "Permanent prestige badge for early community leaders.",
    preview: { gradient: "from-slate-800 to-emerald-400", icon: "shield", animation: "shine" },
    metadata: { label: "OG", badgeTone: "slate" },
  },
  {
    itemId: "badge_founder",
    name: "Founder Badge",
    category: MARKETPLACE_CATEGORIES.BADGES,
    rarity: RARITIES.MYTHIC,
    price: 5000,
    levelRequired: 5,
    description: "Ultra-rare founder badge for the first wave of VibeBook prestige.",
    preview: { gradient: "from-black via-yellow-300 to-white", icon: "crown", animation: "orbit" },
    metadata: { label: "Founder", badgeTone: "black" },
  },
  {
    itemId: "boost_feed_24h",
    name: "Feed Boost",
    category: MARKETPLACE_CATEGORIES.BOOSTS,
    rarity: RARITIES.RARE,
    price: 300,
    durationHours: 24,
    cooldownHours: 6,
    description: "Increase creator score in the main feed for one day.",
    preview: { gradient: "from-emerald-400 to-sky-500", icon: "rocket", animation: "pulse" },
    metadata: { boostType: "feed", multiplier: 1.35, estimatedReach: "1.4x-2.1x" },
  },
  {
    itemId: "boost_explore_12h",
    name: "Explore Boost",
    category: MARKETPLACE_CATEGORIES.BOOSTS,
    rarity: RARITIES.EPIC,
    price: 550,
    durationHours: 12,
    cooldownHours: 8,
    description: "Push a creator into discovery surfaces for faster follower growth.",
    preview: { gradient: "from-cyan-400 to-indigo-600", icon: "search", animation: "shine" },
    metadata: { boostType: "explore", multiplier: 1.5, estimatedReach: "1.8x-2.6x" },
  },
  {
    itemId: "boost_trending_6h",
    name: "Trending Boost",
    category: MARKETPLACE_CATEGORIES.BOOSTS,
    rarity: RARITIES.LEGENDARY,
    price: 950,
    durationHours: 6,
    cooldownHours: 12,
    description: "Short high-impact trending priority with stricter cooldowns.",
    preview: { gradient: "from-orange-400 to-rose-600", icon: "flame", animation: "flicker" },
    metadata: { boostType: "trending", multiplier: 1.85, estimatedReach: "2.2x-3.4x" },
  },
  {
    itemId: "boost_story_24h",
    name: "Story Boost",
    category: MARKETPLACE_CATEGORIES.BOOSTS,
    rarity: RARITIES.COMMON,
    price: 180,
    durationHours: 24,
    cooldownHours: 4,
    description: "Lightweight boost for daily story visibility.",
    preview: { gradient: "from-pink-400 to-yellow-300", icon: "sparkles", animation: "pulse" },
    metadata: { boostType: "story", multiplier: 1.2, estimatedReach: "1.2x-1.7x" },
  },
  {
    itemId: "boost_creator_spotlight",
    name: "Creator Spotlight",
    category: MARKETPLACE_CATEGORIES.BOOSTS,
    rarity: RARITIES.MYTHIC,
    price: 2200,
    durationHours: 8,
    cooldownHours: 24,
    description: "Premium creator spotlight with analytics and active indicator.",
    preview: { gradient: "from-violet-500 via-fuchsia-500 to-amber-300", icon: "crown", animation: "orbit" },
    metadata: { boostType: "spotlight", multiplier: 2.2, estimatedReach: "3x-5x" },
  },
  {
    itemId: "featured_video_24h",
    name: "Featured Video Placement",
    category: MARKETPLACE_CATEGORIES.FEATURED,
    rarity: RARITIES.LEGENDARY,
    price: 1500,
    durationHours: 24,
    cooldownHours: 12,
    description: "Queue a video for featured placement with moderation status.",
    preview: { gradient: "from-slate-950 via-emerald-500 to-yellow-300", icon: "play", animation: "shine" },
    metadata: { placement: "featured_video", estimatedReach: "2.5x-4x" },
  },
  {
    itemId: "reaction_fire_burst",
    name: "Fire Burst",
    category: MARKETPLACE_CATEGORIES.REACTIONS,
    rarity: RARITIES.RARE,
    price: 180,
    description: "Animated fire reaction for comments, chat, and future livestream gifts.",
    preview: { emoji: "🔥", gradient: "from-orange-400 to-red-600", icon: "flame", animation: "burst" },
    metadata: { emoji: "🔥", animation: "fire-burst" },
  },
  {
    itemId: "reaction_crown_drop",
    name: "Crown Drop",
    category: MARKETPLACE_CATEGORIES.REACTIONS,
    rarity: RARITIES.EPIC,
    price: 420,
    description: "Royal reaction that drops a crown over the creator moment.",
    preview: { emoji: "👑", gradient: "from-yellow-300 to-amber-600", icon: "crown", animation: "drop" },
    metadata: { emoji: "👑", animation: "crown-drop" },
  },
  {
    itemId: "reaction_diamond_rain",
    name: "Diamond Rain",
    category: MARKETPLACE_CATEGORIES.REACTIONS,
    rarity: RARITIES.LEGENDARY,
    price: 900,
    description: "Diamond rain animation for premium engagement.",
    preview: { emoji: "💎", gradient: "from-cyan-300 to-violet-600", icon: "gem", animation: "rain" },
    metadata: { emoji: "💎", animation: "diamond-rain" },
  },
  {
    itemId: "reaction_energy_shock",
    name: "Energy Shock",
    category: MARKETPLACE_CATEGORIES.REACTIONS,
    rarity: RARITIES.RARE,
    price: 260,
    description: "Electric reaction for hype moments and creator shoutouts.",
    preview: { emoji: "⚡", gradient: "from-lime-300 to-sky-500", icon: "zap", animation: "shock" },
    metadata: { emoji: "⚡", animation: "energy-shock" },
  },
  {
    itemId: "reaction_rose_explosion",
    name: "Rose Explosion",
    category: MARKETPLACE_CATEGORIES.REACTIONS,
    rarity: RARITIES.COMMON,
    price: 90,
    description: "Rose burst reaction prepared for future live gifting.",
    preview: { emoji: "🌹", gradient: "from-rose-400 to-pink-600", icon: "gift", animation: "burst" },
    metadata: { emoji: "🌹", animation: "rose-explosion" },
  },
  {
    itemId: "theme_dark_neon",
    name: "Dark Neon",
    category: MARKETPLACE_CATEGORIES.THEMES,
    rarity: RARITIES.RARE,
    price: 400,
    description: "Dark profile surface with neon green and cyan energy.",
    preview: { gradient: "from-slate-950 via-emerald-600 to-cyan-400", icon: "sparkles", animation: "pulse" },
    metadata: { themeKey: "dark_neon", background: "dark", accent: "emerald" },
  },
  {
    itemId: "theme_gold_elite",
    name: "Gold Elite",
    category: MARKETPLACE_CATEGORIES.THEMES,
    rarity: RARITIES.EPIC,
    price: 850,
    description: "Gold creator profile theme for premium status pages.",
    preview: { gradient: "from-zinc-950 via-amber-400 to-yellow-200", icon: "crown", animation: "shine" },
    metadata: { themeKey: "gold_elite", background: "black", accent: "gold" },
  },
  {
    itemId: "theme_cyber_blue",
    name: "Cyber Blue",
    category: MARKETPLACE_CATEGORIES.THEMES,
    rarity: RARITIES.RARE,
    price: 520,
    description: "Blue cyber profile theme for tech, gaming, and dance creators.",
    preview: { gradient: "from-slate-950 via-blue-600 to-teal-300", icon: "zap", animation: "pulse" },
    metadata: { themeKey: "cyber_blue", background: "dark", accent: "blue" },
  },
  {
    itemId: "theme_fire_red",
    name: "Fire Red",
    category: MARKETPLACE_CATEGORIES.THEMES,
    rarity: RARITIES.EPIC,
    price: 650,
    description: "High-heat profile theme for viral creators.",
    preview: { gradient: "from-zinc-950 via-red-600 to-orange-400", icon: "flame", animation: "flicker" },
    metadata: { themeKey: "fire_red", background: "dark", accent: "red" },
  },
  {
    itemId: "theme_aurora_gradient",
    name: "Aurora Gradient",
    category: MARKETPLACE_CATEGORIES.THEMES,
    rarity: RARITIES.LEGENDARY,
    price: 1400,
    description: "Aurora profile theme with premium gradient identity.",
    preview: { gradient: "from-emerald-300 via-sky-400 to-fuchsia-500", icon: "sparkles", animation: "wave" },
    metadata: { themeKey: "aurora_gradient", background: "aurora", accent: "multi" },
  },
  {
    itemId: "theme_rwanda_sunset",
    name: "Rwanda Sunset",
    category: MARKETPLACE_CATEGORIES.THEMES,
    rarity: RARITIES.SEASONAL,
    price: 950,
    description: "Warm Rwanda-inspired premium profile theme with sunrise gold, sky blue, and green accents.",
    preview: { gradient: "from-sky-500 via-yellow-300 to-emerald-500", icon: "star", animation: "wave" },
    metadata: { themeKey: "rwanda_sunset", background: "sunset", accent: "rwanda", collection: "Rwanda Premium Themes" },
  },
  {
    itemId: "theme_vip_midnight",
    name: "VIP Midnight",
    category: MARKETPLACE_CATEGORIES.THEMES,
    rarity: RARITIES.LEGENDARY,
    price: 1750,
    levelRequired: 3,
    description: "Dark glass VIP profile theme with gold rails, quiet glow, and creator status polish.",
    preview: { gradient: "from-zinc-950 via-amber-500 to-white", icon: "crown", animation: "shine" },
    metadata: { themeKey: "vip_midnight", background: "midnight", accent: "gold", collection: "VIP Profile Themes" },
  },
  {
    itemId: "badge_kigali_elite",
    name: "Kigali Elite",
    category: MARKETPLACE_CATEGORIES.BADGES,
    rarity: RARITIES.SEASONAL,
    price: 1300,
    levelRequired: 2,
    description: "Seasonal Kigali-inspired badge for culture-forward creators and premium profile loadouts.",
    preview: { gradient: "from-indigo-950 via-fuchsia-600 to-yellow-300", icon: "medal", animation: "shine" },
    metadata: { label: "Kigali Elite", badgeTone: "violet", collection: "Rwanda Premium Badges" },
  },
  {
    itemId: "badge_vip_creator",
    name: "VIP Creator",
    category: MARKETPLACE_CATEGORIES.BADGES,
    rarity: RARITIES.LEGENDARY,
    price: 2400,
    levelRequired: 4,
    description: "Premium VIP badge built for high-status creator cards, profiles, comments, and chats.",
    preview: { gradient: "from-zinc-950 via-amber-500 to-white", icon: "shield-check", animation: "orbit" },
    metadata: { label: "VIP", badgeTone: "gold", collection: "VIP Badges" },
  },
  {
    itemId: "gift_live_future_pack",
    name: "Future Live Gifts Pack",
    category: MARKETPLACE_CATEGORIES.GIFTS,
    rarity: RARITIES.SEASONAL,
    price: 0,
    description: "Reserved catalog slot for livestream gifting expansion.",
    preview: { gradient: "from-slate-700 to-slate-950", icon: "gift", animation: "pulse" },
    metadata: { comingSoon: true },
    status: "coming_soon",
  },
];

module.exports = {
  DEFAULT_MARKETPLACE_ITEMS,
  MARKETPLACE_CATEGORIES,
  RARITIES,
};
